# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w66tQ6zmnUUOqpSeOn7oyps9ID3HLo7f
"""

a = [2,4,6,8,10]
print("square of the given list:")
for i in a:
  print(i**2)
print("cube of the given list:")
for i in a:
  print(i**3)
print("forthroot of the given list:")
for i in a:
  print(i**4)
